### ISSUE TITLE
Add new resources (video_show, video_category)

### ISSUE THREAD

**Issue by xaro** [claflamme/node-giantbomb#1]
There are some new endpoints that were added to the API (http://www.giantbomb.com/forums/api-developers-3017/notice-video-type-and-video-types-endpoint-depreca-1807405/#6). They should be added to the resources file.

**Comment by claflamme** [comment]
For sure, I'll take a look at those. Thanks for the heads up. 👍

**Comment by claflamme** [comment]
I added the new endpoints and removed the deprecated one. A new 2.0.0 release is on npm now.
