### ISSUE TITLE
Duplicates returned for /games/ endpoint.

### ISSUE THREAD

**Issue by markadrake** [claflamme/node-giantbomb#2]
I have some otherwise straight forward code to download a list of games from the GiantBomb API. To cut back on how often it's necessary to go through this process, I store the JSON result as a file on the server. **Everything works wonderfully**, however I noticed some more recent games are missing. I also had some trouble when looking at the IDs because there are duplicates throughout. 

What has been your experience in testing? Do you see duplicates returned, games that are missing, something I'm oblivious too in my code sample below? I appreciate it. 

```
		let config = {
			page: 1,
			perPage: 100,
			fields: [
				"aliases",
				"api_detail_url",
				"date_added",
				"date_last_updated",
				"expected_release_month",
				"expected_release_quarter",
				"expected_release_year",
				"id",
				"image",
				"name",
				"original_game_rating",
				"original_release_date",
				"platforms",
				"site_detail_url"
			]
		};

		let totalPages = 550; // will be set to the real value later

		let intervalId = setInterval(() => {
			let currentConfig = Object.assign({}, config);
			if (currentConfig.page >= totalPages) clearInterval(intervalId);
			console.log(`Requesting page ${currentConfig.page} of ${totalPages}`);
			gb.games.list(currentConfig, (err, res, json) => {
				totalPages = json.number_of_total_pages;
				fs.writeFileSync(`./data/games/page-${currentConfig.page}.json`, JSON.stringify(json, null, 4));
			});
			config.page++;
		}, 1100); // to be safe stagger our api calls to less than 1/sec rate
```

**Comment by claflamme** [comment]
I haven't had any issues with duplicates or missing items, but I haven't been looking for them either.

I imagine the duplicates are resulting from data changing as the crawl is running. If games are added or removed, that could alter the results, potentially having them appear on different pages. The games are also sorted by `number_of_user_reviews` by default, which could have the same effect as reviews are added/removed.

If you have any specific examples of missing or duplicated items, let me know and I'll check it out. If it's a data issue, I'll likely not be able to do anything. Results are pulled almost unmodified from the API, this package only provides a JS wrapper for it.
