### ISSUE TITLE
Add Resource: DLCS / DLC

### ISSUE THREAD

**Issue by markadrake** [claflamme/node-giantbomb#3]
I'm not sure if this is a new resource or not - but could we add this to the list?

DLC: https://www.giantbomb.com/api/documentation#toc-0-12
DLCS: https://www.giantbomb.com/api/documentation#toc-0-13

**Comment by claflamme** [comment]
Must be a new(er) one, I think I did a top-to-bottom pass before v1. Anyways, I added a new `dlc` resource with `get`, `list`, and `search` methods:

https://github.com/claflamme/node-giantbomb/wiki/dlc

Let me know if there are any issues, and thanks for the heads up!
